import Head from "next/head";
import { IProductItem } from "../interfaces";
import { MainContainer } from "../styles/shared";
import ListPage from "../views/listpage";
import FAKE_PRODUCTS_LIST from "../views/listpage/fakeProducts.json";

interface HomeProps {
  data: IProductItem[];
}

const Home = ({ data }: HomeProps) => {
  return (
    <div>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <ListPage data={data} />
      </MainContainer>
    </div>
  );
};

export async function getServerSideProps() {
  return {
    props: { data: FAKE_PRODUCTS_LIST },
  };
}

export default Home;
