import Head from "next/head";
import { IProductItem } from "../interfaces";
import { getProducts } from "../services";
import { MainContainer } from "../styles/shared";
import ProductList from "../views/ProductList";
import FAKE_PRODUCTS_LIST from "../views/ProductList/fakeProducts.json";

interface HomeProps {
  data: IProductItem[];
}

const Home = ({ data }: HomeProps) => {
  return (
    <div>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <ProductList data={data} />
      </MainContainer>
    </div>
  );
};

export async function getServerSideProps() {
  try {
    const { data } = await getProducts();

    return {
      props: { data },
    };
  } catch (err) {
    console.error(err);
    return {
      props: {},
    };
  }
}

export default Home;
